### ISSUE TITLE
Epic: phase 0

### ISSUE THREAD

**Issue by arsenyjin** [Curve-Labs/prime-dao#1]
Phase 0 back-end most likely is:

- [ ] Set-up DAO using [DAOstack framework](https://github.com/daostack)
- [ ] Integrate [openraise bonding curve](https://github.com/Curve-Labs/openraise-dapp)
- [ ] Integrate multisig / contract so we can vest funds to the DAO with over time
- [ ] Link ENS website to DAO
- [ ] Graph assignment
- [ ] Possible reputation snapshot/reputation mechanics (e.g. we take a snapshot of holders of a given token at a given time and they can redeem reputation)
